Importing open ai gym and the package

In [1]:
import gym
import numpy as np
import n_server

Setting up the configuration for the environment

In [2]:
CONFIG = {'rho': .8, 'N': 10, 'h1': 3, 'h2': 1, 'starting_state':[0,0]}

Making an instance of the environment

In [3]:
env = gym.make('NServer-v0', config=CONFIG)

In [4]:
print(env.state)
print(env.action_space)
print(env.observation_space) # openAI calles states observations :/

[0 0]
MultiDiscrete([2 4])
MultiDiscrete([11 11])


Testing the step function

In [5]:
env.state = [0,0]
print(env.step([0,2]))
print('***')
env.state = [5,3]
print(env.step([1,2]))

(array([1, 0]), 0.0, False, {})
***
(array([6, 3]), -4.66321243523316, False, {})


test sample uniformly from action space at random

In [6]:
env.action_space.sample()

array([1, 1])

Simulating randomized policy

In [7]:
N = 500
gamma = 0.9


env.reset()
tot_reward = 0
for i in range(N):
    _, reward, _, _ = env.step(env.action_space.sample())
    tot_reward += (gamma**i)*reward
print(tot_reward)

-8.471217873625323
